# Generated by Django 5.1.2 on 2024-10-31 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('secciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones.seccion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cuenta_por_cobrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facturacion.cuentaporcobrar'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='secciones_tarifa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secciones.seccion'),
        ),
    ]
